import { resolve, dirname, basename } from "path";
import { existsSync, readFileSync, mkdirSync, writeFileSync } from "fs";
import { spawnSync } from "child_process";
import { createRequire } from "module";
import { exitWithError, AddfoxError, ADDFOX_ERROR_CODES, warn } from "@addfox/common";
import {
  getResolvedRstestConfigFilePath,
  getResolvedConfigFilePath,
  loadConfigFile,
  ADDFOX_OUTPUT_ROOT,
  type AddfoxTestConfig,
} from "@addfox/core";
import {
  detectFromLockfile,
  getAddCommand,
  getMissingPackages,
} from "@addfox/pkg-manager";

const require = createRequire(import.meta.url);

/** Generated rstest wrapper config name, written under <root>/.addfox/ */
const GENERATED_RSTEST_CONFIG = "rstest.config.ts";

type TestConfigResolution =
  | { mode: "configFile"; configPath: string }
  | { mode: "testField"; testField: AddfoxTestConfig; addfoxConfigPath: string }
  | { mode: "none" };

/** Load the test field from addfox.config; null when absent or unloadable. */
function loadTestField(projectRoot: string, silent: boolean): AddfoxTestConfig | null {
  try {
    const userConfig = loadConfigFile(projectRoot);
    return userConfig?.test ?? null;
  } catch (e) {
    if (silent) return null;
    throw e;
  }
}

function validateTestFramework(framework: unknown): void {
  if (framework === undefined || framework === "rstest") return;
  throw new AddfoxError({
    code: ADDFOX_ERROR_CODES.INVALID_ARGUMENT,
    message: `Unsupported test framework: ${String(framework)}`,
    details: `addfox.config test.framework is "${String(framework)}"`,
    hint: 'Only "rstest" is currently supported. Omit the framework field (defaults to "rstest").',
  });
}

/**
 * Resolve where rstest config comes from.
 * Precedence (industry convention, same as vitest.config over vite.config's test field):
 * rstest.config.* file wins over the addfox.config `test` field.
 */
export function resolveTestConfig(projectRoot: string): TestConfigResolution {
  const rstestConfigPath = getResolvedRstestConfigFilePath(projectRoot);

  if (rstestConfigPath) {
    // Broken addfox.config must not block tests when the rstest config file wins.
    const testField = loadTestField(projectRoot, true);
    if (testField) {
      warn(
        "The `test` field in addfox.config is ignored because rstest.config.* takes precedence."
      );
    }
    return { mode: "configFile", configPath: rstestConfigPath };
  }

  const testField = loadTestField(projectRoot, false);
  if (testField) {
    validateTestFramework(testField.framework);
    const addfoxConfigPath = getResolvedConfigFilePath(projectRoot);
    if (!addfoxConfigPath) {
      // Unreachable: loadConfigFile succeeded, so a config file exists.
      return { mode: "none" };
    }
    return { mode: "testField", testField, addfoxConfigPath };
  }

  return { mode: "none" };
}

/**
 * Generate .addfox/rstest.config.ts that re-exports the addfox.config `test` field.
 * Re-importing addfox.config keeps functions/reporters alive (unlike serialization).
 */
export function writeGeneratedRstestConfig(
  projectRoot: string,
  addfoxConfigPath: string
): string {
  const importPath = `../${basename(addfoxConfigPath)}`;
  const content = `// Auto-generated by addfox. Do not edit.
import { defineConfig } from "@rstest/core";
// @ts-ignore
import addfoxConfig from "${importPath}";

// "framework" is an addfox reserved discriminator; strip it before passing through to Rstest.
const { framework: _framework, ...rstestConfig } =
  (addfoxConfig as { test?: Record<string, unknown> }).test ?? {};
export default defineConfig({ root: ${JSON.stringify(projectRoot)}, ...rstestConfig });
`;
  const outDir = resolve(projectRoot, ADDFOX_OUTPUT_ROOT);
  mkdirSync(outDir, { recursive: true });
  const outPath = resolve(outDir, GENERATED_RSTEST_CONFIG);
  writeFileSync(outPath, content, "utf-8");
  return outPath;
}

/** Detect browser.enabled from rstest config via regex (avoids loading .ts). */
function isRstestBrowserEnabled(projectRoot: string): boolean {
  const configPath = getResolvedRstestConfigFilePath(projectRoot);
  if (!configPath) return false;
  try {
    const content = readFileSync(configPath, "utf-8");
    return (
      /browser\s*:\s*\{[^}]*enabled\s*:\s*true/.test(content) ||
      /browser\.enabled\s*===?\s*true/.test(content)
    );
  } catch {
    return false;
  }
}

/** Detect browser.enabled from the live addfox.config `test` field object. */
export function isBrowserEnabledFromTestField(testField: AddfoxTestConfig): boolean {
  const browser = (testField as { browser?: { enabled?: boolean } }).browser;
  return browser?.enabled === true;
}

function getRequiredTestPackages(
  projectRoot: string,
  resolution: TestConfigResolution
): string[] {
  const required: string[] = ["@rstest/core"];
  const browserEnabled =
    resolution.mode === "testField"
      ? isBrowserEnabledFromTestField(resolution.testField)
      : isRstestBrowserEnabled(projectRoot);
  if (browserEnabled) {
    required.push("@rstest/browser", "playwright");
  }
  return required;
}

function getRstestBinPath(projectRoot: string): string {
  const binDir = resolve(projectRoot, "node_modules", ".bin");
  const name = process.platform === "win32" ? "rstest.cmd" : "rstest";
  const p = resolve(binDir, name);
  if (existsSync(p)) return p;
  const fallback = resolve(binDir, "rstest");
  if (existsSync(fallback)) return fallback;
  try {
    const corePkgPath = require.resolve("@rstest/core/package.json", {
      paths: [projectRoot],
    });
    const coreDir = dirname(corePkgPath);
    const binInCore = resolve(coreDir, "bin", "rstest.js");
    if (existsSync(binInCore)) return binInCore;
  } catch {
    /* fall through to exitWithError */
  }
  exitWithError(
    new Error(
      "rstest binary not found in node_modules/.bin after installing @rstest/core"
    )
  );
}

function runRstest(projectRoot: string, restArgs: string[]): number {
  const rstestBin = getRstestBinPath(projectRoot);
  const result = spawnSync(rstestBin, restArgs, {
    cwd: projectRoot,
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  return result.status ?? 0;
}

/**
 * Run addfox test: resolve rstest config (rstest.config.* file first, then the
 * addfox.config `test` field), install missing deps, forward to rstest.
 */
export async function runTest(projectRoot: string, argv: string[]): Promise<void> {
  const resolution = resolveTestConfig(projectRoot);

  if (resolution.mode === "none") {
    const files = "rstest.config.cts, rstest.config.mts, rstest.config.cjs, rstest.config.js, rstest.config.ts, rstest.config.mjs";
    throw new AddfoxError({
      code: ADDFOX_ERROR_CODES.RSTEST_CONFIG_NOT_FOUND,
      message: "Rstest config not found",
      details: `No rstest.config.* or addfox.config \`test\` field found under ${projectRoot}`,
      hint: `Create one of: ${files}, or add a \`test\` field to addfox.config`,
    });
  }

  const required = getRequiredTestPackages(projectRoot, resolution);
  const missing = getMissingPackages(projectRoot, required);
  if (missing.length > 0) {
    const pm = detectFromLockfile(projectRoot);
    const installCmd = getAddCommand(pm, missing.join(" "), true);
    exitWithError(
      new Error(
        `Missing test dependencies: ${missing.join(", ")}. Please run:\n  ${installCmd}`
      )
    );
  }

  const restArgs = argv.slice(1);
  const args =
    resolution.mode === "testField"
      ? [
          "--config",
          writeGeneratedRstestConfig(projectRoot, resolution.addfoxConfigPath),
          ...restArgs,
        ]
      : restArgs;
  const code = runRstest(projectRoot, args);
  process.exit(code);
}
